platform :ios, '12.0'

install! 'cocoapods', :disable_input_output_paths => true


flutter_application_path = '../lb_flutter/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


  
target 'flutterTest' do

  install_all_flutter_pods(flutter_application_path)
    post_install do |installer|
      flutter_post_install(installer) if defined?(flutter_post_install)
  end
  
end
